### ISSUE TITLE
euclidean distance should be sqrt((x1-x2)**2+(y1-y2)**2))

### ISSUE THREAD

**Issue by tanishsahu42** [python-engineer/MLfromscratch#5]
euclidean distance should be sqrt((x1-x2)**2+(y1-y2)**2))
or in more advanced way
euclid_dist= np.linalg.norm(np.array(feature)-np.array(predict))

def knn(data,predict,k=3):
    if len(data)>=3:
        warnings.warn("len should be less than 3")
    distances=[]
    for group in data:
        for feature in data[group]:
            
            euclid= np.linalg.norm(np.array(feature)-np.array(predict))
          
            distances.append([euclid,group])
    vote=[i[1]for i in sorted(distances)[:k]]
    vote_result=Counter(vote).most_common(1)[0][0]
    
 return vote_result

**Comment by patrickloeber** [comment]
My formula is exactly what your first formula is saying. we sum over each difference and square it. it might be confusing since the points are named x1 and x2. maybe a better naming would be p1 and p2, and then each point p1 has (x1,y1,z1,...).

you can test my formula and compare with this. It's the same result.
def ec(x1,x2):
    return np.linalg.norm(x1-x2)
